### NumPy Exercises
- Learning numpy array structures
- Comprehending difference between numpy arrays and python lists
- Practice iterating through numpy arrays

In [22]:
import numpy as np

In [23]:
# Use the following code for the questions below:

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [24]:
# How many negative numbers are there?
# (To prove to myself I know how to use .shape in this context)
a[a < 0].shape

print(f"There are {a[a < 0].shape} negative numbers in this array")

There are (4,) negative numbers in this array


In [25]:
# Using len:

len(a[a < 0])

4

In [26]:
# How many positive numbers are there?
# 0 doesn't count, as it is this origin integer.

a[a > 0].shape

(5,)

In [27]:
# How many even positive numbers are there?

a[(a > 0) & (a % 2 == 0)].shape

(3,)

In [28]:
# If you were to add 3 to each data point, how many positive numbers would there be?

a[(a + 3) > 0].shape

(10,)

In [29]:
# If you squared each number, what would the new mean and standard deviation be?

(a ** 2).std()
(a ** 2).mean()

# Printing results for output to screen:
print(f"The new std. dev would be: {(a ** 2).std()}")
print(f"The new mean would be: {(a ** 2).mean()}")

The new std. dev would be: 144.0243035046516
The new mean would be: 74.0


In [30]:
# A common statistical operation on a dataset is centering. This means to adjust 
# the data such that the center of the data is at 0. This is done by subtracting the mean 
# from each data point. Center the data set.

a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [31]:
# Using list comphrension: (Again, I'm doing this just so I can wrap my head around what numpy is doing.)

array_mean = a.mean()
array_mean

centered_array = [x - array_mean for x in a]
centered_array

[1.0, 7.0, 9.0, 20.0, -5.0, -4.0, -3.0, -3.0, -3.0, -9.0, 0.0, -10.0]

#### Calculate the z-score for each data point. Recall that the z-score is given by:
$Z = (x - u) / std$


In [32]:
z_score = (a - a.mean())/a.std()
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [33]:
## Setup 1
a2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Use python's built in functionality/operators to determine the following:

In [34]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

# I think these first four are pretty straightforward unless I'm missing something in the instructions.

sum_of_a = sum(a2)
sum_of_a

55

In [35]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a2)
min_of_a

1

In [36]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max(a2)
max_of_a

10

In [37]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = sum(a2) / len(a2)
mean_of_a

5.5

In [38]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

# I decided to use a function since that's what made the most sense to me in this moment. 
# I'm sure there is a way to use list comprehension, but this is what clicked for me in the moment. 
# And I figured that was ok to do since functions are a based part of Python, unless I mis-read the instructions

def multiply_list(value):
    result = 1
    for x in value:
        result = result * x
    return result


product_of_a = multiply_list(a2)
product_of_a

3628800

In [39]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number 
# in a squared like [1, 4, 9, 16, 25...]

# Still trying to use list comprehensions wherever I can, since it look a lot of work for those to finally click in my mind.
# Don't want to lose that in my short-term memory!

# I'm iterating through the a2 list, and squaring each element of that list, and then returning the results in a new list: squares_of_a

squares_of_a = ([i ** 2 for i in a2])
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [40]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

# Finding the numbers in the list that are not divisible by 0, and creating a new list from those odd numbers.

odds_in_a = [x for x in a2 if x % 2 == 1]
odds_in_a

[1, 3, 5, 7, 9]

In [41]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

# Finding the numbers in the list that are divisible by 0, and creating a new list from those even numbers.

evens_in_a = [x for x in a2 if x % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

In [42]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

b = [
    [3, 4, 5],
    [6, 7, 8]
    ]

In [43]:
# I figured out to not use list comprehensions in [] brackets, but I don't fully understand why I can't use the [].

# Tried using brackets and get an invalid syntax error...

# sum_of_b = sum[sum(x) for x in b]f
# sum_of_b

# Found this solution here:
# https://stackoverflow.com/questions/9497290/how-would-i-sum-a-multi-dimensional-array-in-the-most-succinct-python

In [44]:
# Find the sum of a 2d list

sum_of_b = sum(sum(x) for x in b)
sum_of_b

33

In [45]:
# Find the min of a 2d list

min_of_b = min(min(x) for x in b)
min_of_b

3

In [46]:
# Find the max of a 2d list

max_of_b = max(max(x) for x in b)
max_of_b

8

In [47]:
# Find the average of a 2d list.
# This one was a bit more tricky, as I was first trying len([len(x) for x in b]). But that's not the right answer, as I needed to sum the results of that first len(), which is 6.
# Then I could take the sum of all elements / the sum of all the lengths = average of b.

average_of_b = (sum(sum(x) for x in b)) / (sum(len(x) for x in b))
average_of_b

5.5

In [48]:
# Can't do this using the function I had before, as this is a 2 dimensional list.

# def multiply_list_b(value):
#     result = 1
#     for x in value:
#         result = result * x
#     return result


# product_of_b = multiply_list_b(b)
# product_of_b

In [49]:
# Refactorting b as a numpy array:

b = [
    [3, 4, 5],
    [6, 7, 8]
    ]


ba = np.array([[3, 4, 5],
                [6, 7, 8]])

In [50]:
npb = np.array(b)
npb

array([[3, 4, 5],
       [6, 7, 8]])

In [51]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**

# Original code:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

# Using numpy's sum() function the code becomes:
ba.sum()

33

In [52]:
# Exercise 2 - refactor the following to use numpy. 

# This is using list comprehension:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

# Using numpy's min function:
ba.min()

3

In [53]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

# Python list comprehension:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

# Using numpy's max():
ba.max()

8

In [54]:
# Exercise 4 - refactor the following using numpy to find the mean of b

# Python list comprehension:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Using numpy's max():
ba.max()

8

In [55]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Using numpy:
ba.prod()


20160

In [56]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
squares_of_b

# Using numpy:
np.square(ba)


array([[ 9, 16, 25],
       [36, 49, 64]])

In [57]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
# Using numpy:
odds_in_b = (ba[ba % 2 == 1])
print(odds_in_b)

# Link to article that I used for help:
# https://stackoverflow.com/questions/51617421/how-to-get-only-odd-numbers-in-array-and-square-them-using-numpy-for-python

[3 5 7]


In [58]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
# Using numpy:
evens_in_b = (ba[ba % 2 == 0])
print(evens_in_b)

[4 6 8]


In [59]:
# Exercise 9 - print out the shape of the array b.
print(np.shape(ba))

# Array has 2 dimensions, and each dimension (list) has 3 elements.

(2, 3)


In [60]:
# Exercise 10 - transpose the array b.

np.transpose(ba)
# This is cool - so I can reorient the order of any 2d (or multidimensional) array. I can see that will be very useful and powerful going forward.

array([[3, 6],
       [4, 7],
       [5, 8]])

In [61]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

flatb = ba.flatten()
print(flatb)

# Got help from this article:
# https://www.kite.com/python/answers/how-to-convert-a-2d-numpy-array-to-a-1d-array-in-python

[3 4 5 6 7 8]


In [62]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

# Ok, so I'll actually use reshape on this one.

baarrsix = ba.reshape(6, 1)
print(baarrsix)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [63]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

c = np.array(c)

In [64]:
# Exercise 1 - Find the min, max, sum, and product of c.

c.max()
c.min()
c.sum()
c.prod()

362880

In [65]:
# Exercise 2 - Determine the standard deviation of c.

c.std()

2.581988897471611

In [66]:
# Exercise 3 - Determine the variance of c.

c.var()

6.666666666666667

In [67]:
print(np.shape(c))

(3, 3)


In [68]:
# Exercise 5 - Transpose c and print out transposed result.

c.transpose()
print(np.shape(c))

(3, 3)


In [69]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [71]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

c_times_c = np.sum(c * (np.transpose(c)))
c_times_c

261

In [73]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

c_prod_c = np.prod(c * (np.transpose(c)))
c_prod_c

131681894400

In [78]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Changing to numpy array:
dnp = np.array(d)
dnp

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [80]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(dnp)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [81]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(dnp)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [82]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(dnp)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [85]:
# Exercise 4 - Find all the negative numbers in d

negative_in_d = (dnp[dnp < 0])
print(negative_in_d)

[-90 -30 -45 -45]


In [86]:
# Exercise 5 - Find all the positive numbers in d

positive_in_d = (dnp[dnp > 0])
print(positive_in_d)

[ 90  30  45 120 180  45 270  90  60  45  90 180]


In [88]:
# Exercise 6 - Return an array of only the unique numbers in d

dnp = np.array(d)
print(dnp)
# Printed out dnp array here so I could visually compare the results of the np.unique() function. Just for a "gut check".

np.unique(dnp)

[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]


array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [89]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(dnp))

11

In [90]:
# Exercise 8 - Print out the shape of d.

np.shape(dnp)

(3, 6)

In [99]:
# Exercise 9 - Transpose and then print out the shape of d.

print(np.transpose(dnp))

# For further personal comprehension of what transpose is doing, I'm going to use shape on this new array:
newshape_dnp = np.transpose(dnp)
print("     ")
print(np.shape(newshape_dnp))

# So the shape is the opposite, (6, 3), which is the opposite of (3, 6).

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]
     
(6, 3)


In [100]:
# Exercise 10 - Reshape d into an array of 9 x 2

np.reshape(dnp, (9, 2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])